### ISSUE TITLE
Blank page on all forum

### ISSUE THREAD

**Issue by Galixte** [RMcGirr83/phpBB-3.1-elonw#3]
Hi @RMcGirr83,

after activated your extension with the latest snapshot, your last commits seems to be the reason.

**Comment by RMcGirr83** [comment]
Working on it.  Damn smartgit screwed up the files.  Work in progress.

**Comment by Galixte** [comment]
Ok, thanks for information.

**Comment by RMcGirr83** [comment]
Fixed with latest commit.
