### ISSUE TITLE
Is not compatible with bbcode media

### ISSUE THREAD

**Issue by GM-GH** [rmcgirr83/phpBB-3.1-elonw#7]
Is not compatible with very popular bbcode media (https://www.phpbb.com/customise/db/bbcode/media/)
Please fix.

**Comment by rmcgirr83** [comment]
Define "not compatible" exactly what is the issue.

**Comment by GM-GH** [comment]
When I enable your extension (phpBB-3.1-ext-ELONW) media tag doesn't work.
![wrong bbcode](https://cloud.githubusercontent.com/assets/20455688/16841304/47324a24-49e1-11e6-8abf-6bf15a3a75ac.jpg)

**Comment by rmcgirr83** [comment]
It works, I just tested it.

http://rmcgirr83.org/viewtopic.php?f=2&t=6
