### ISSUE TITLE
Extension breaks the [video] bbcode

### ISSUE THREAD

**Issue by speller** [rmcgirr83/phpBB-3.1-elonw#8]
This extension breaks this http://www.phpbbguru.net/community/viewtopic.php?t=36630 [video] bbcode.

**Comment by rmcgirr83** [comment]
Probably because that code has this in it
`<a style='color: #555; text-decoration: none;' href='http://phpbbex.com/' target='_blank'>phpBB &#91;video&#93;</a>`
Not sure why you would want to hot link js code from phpbbex.com

**Comment by speller** [comment]
Because the author of the video bbcode provide an universal library to easily embed videos from multiple video hostings using any type of its links by the single bbcode. It is unable to do the same with pure phpBB functionality without patching sources (or didn't found similar phpBB extension?)

**Comment by rmcgirr83** [comment]
Can't [reproduce this] (http://rmcgirr83.org/viewtopic.php?f=2&t=6)

**Comment by speller** [comment]
As I can see right now - link to phpbb.com not opened in new window... Anyway, when I disabled your extension the [video] bbcode started working. When I enable it - video don't work.

**Comment by rmcgirr83** [comment]
Look again.

**Comment by speller** [comment]
Now working... Can this issue be caused by theme? In my forum I use the Elegance Steel Blue theme.

**Comment by speller** [comment]
Also, I do not see any errors in the F12 browser console in the Chrome.

**Comment by rmcgirr83** [comment]
Provide a link so I can see what's going on.

**Comment by speller** [comment]
I tried to use prosilver and stillnot working...

Look at this post: http://windom-club.ru/forum/viewtopic.php?f=1&t=7711&p=67706#p67706 . The [video] not working. Forum in Russian only and do not contain any patches. Only your extension and custom bbcode.

**Comment by speller** [comment]
As you can see here: http://www.phpbbguru.net/community/viewtopic.php?t=36630&start=300 (using google translate if you don't understand Russian) many users claim they have troubles using your extension with the [video] bbcode. Also, I found it just now, the bbcode author suggest the fix: http://www.phpbbguru.net/community/viewtopic.php?t=36630&start=285#p472404 (to remove the `.attr("rel", "nofollow")` code)

**Comment by rmcgirr83** [comment]
It states "Wrong bbcode"

**Comment by speller** [comment]
Yes, and if I turn off your extension it will work. Check now.

**Comment by rmcgirr83** [comment]
I pushed new code this AM which is waiting in validation queue at phpbb.com.  Disable the extension in the ACP, download the files from here and upload to your forum, then re-enable the extension in the ACP and see if that fixes it.

**Comment by rmcgirr83** [comment]
You could also do [this] (http://www.phpbbguru.net/community/viewtopic.php?p=491766#p491766)

**Comment by speller** [comment]
I downloaded new version and I confirm it work fine with the bbcode. You can check at the link I provided above. 
Thank you!

**Comment by rmcgirr83** [comment]
You're welcome
